[#30955] YSQL: Tablelocks: Fix NON CONCURRENT INDEX inconsistency when issued in parallel to active DML
Summary:
**Background**
When `yb_ddl_transaction_block_enabled` GUC is enabled, we use `PgClientSessionKind::kPlain` while performing read ops to the pg catalog tables for DDLs. This sets the read time for the session, and the same is used for the subsequent statements unless a different read time manipulator/read serial number is provided or the snapshot is switched in pggate layer.

When `yb_enable_concurrent_ddl` GUC is enabled, we use `PgClientSessionKind::kPlain` while performing all read ops to the storage layer. Read time manipulation is done accordingly for DML ops inside the transaction based on the isolation level etc.

**Problem**
1. With object locking enabled (transaction ddl enabled too, since object locking takes a dependency on it) and concurrent ddl disabled, we ran into an index inconsistency issue where the CREATE INDEX failed to observe an UPDATE that ran in parallel to it and finished before CREATE INDEX acquired `SHARE` lock (`SHARE` conflicts with `ROW EXCLUSIVE` and hence the CREATE INDEX statement rightly waits for the UPDATE to finish). The following is the sequence of events
```
begin;
update test set v=100 where k=4;
                                        begin;
                                        create index test_idx on test(v);
                                        -- performs reads on some pg catalog tables
                                        -- and blocks on SHARE lock request on the test table.
commit;
                                        -- resumes now
                                        -- but still ends up using the old read time, and hence doesn't
                                        -- read the updated v=100, and leads to an inconsistency
```
Some debug and failure logs for the session on the right executing create index.
```
22:02:49.867434 .. Performing RPC: pid=452518, session_kind=kPlain, ops=[R:pg_yb_catalog_version], 22:02:49.882989 .. read_time=not set yet
Performing RPC: pid=452518, session_kind=kPlain, ops=[R:pg_event_trigger], read_time={ read: { days: 20550 time: 22:02:49.870949 }
-- tries to acquire the SHARE lock, gets blocked until the blocker commits.
-- blocker commits with commit time 22:02:54.897253
-- some more ops on catalog tables
22:02:55.642416 .. Performing RPC: pid=452518, session_kind=kPlain, ops=[R:test], read_time={ read: { days: 20550 time: 22:02:49.870949 }
```
```
ERROR:  inconsistent index row due to binary mismatch of key attribute
DETAIL:  index: 'idx_test', ybbasectid: '\x479eaf48800000042121', index attnum: 1
```
YB fails to observe the latest update since it uses the same read time from the earlier catalog read ops that were perform prior to obtaining the `SHARE` lock on the base relation.

Note that the above issue goes away with concurrent ddl enabled (`yb_enable_concurrent_ddl `), because with concurrent ddl though we use `kPlain` for all catalog reads, we seem to have read serial manipulation which takes care of setting the read time appropriately. Below are a few logs for the session executing create index.
```
Performing RPC: pid=287403, session_kind=kPlain, ops=[W:pg_class], read_time={ read: { days: 20564 time: 16:23:25.348024 } ... , read_time_serial_no=8, ...
... Clamping read time to { read: { days: 20564 time: 16:23:25.468030 } ... }
Performing RPC: pid=287403, session_kind=kPlain, ops=[W:pg_class_relname_nsp_index], read_time={ read: { days: 20564 time: 16:23:25.468030 } ... , read_time_serial_no=9, ...
... Clamping read time to { read: { days: 20564 time: 16:23:25.665316 } ... }
--- tries acquiring SHARE lock and blocks until the UPDATE finishes
Performing RPC: pid=287403, session_kind=kPlain, ops=[R:test], read_time={ read: { days: 20564 time: 16:23:25.665316 } ... }, read_time_serial_no=6 ...
```

Also, note that non concurrent index creation isn't supported without object locking since it can lead to index corruption like below when issued in concurrent to writes.
```
begin;
update test set v=100 where k=4;
                                        begin;
                                        create index test_idx on test(v);
                                        commit;
commit;
select * from test where v=4;
 k |  v
---+-----
 4 | 100
(1 row)

select * from test where v=100;
 k | v
---+---
(0 rows)
```

2. With `yb_enable_concurrent_ddl` enabled, we run into the same issue with a different example where the transaction could already have set a read time due to an already issued DML.
```
begin;
update test set v=100 where k=4;
                                        begin;
                                        select * from test; -- sets the read time
                                        create index test_idx on test(v);
                                        -- blocks on SHARE lock request on the test table.
commit;
                                        -- resumes now
                                        -- but still ends up using the old read time, and hence doesn't
                                        -- read the updated v=100, and leads to an inconsistency
```

**Fix**
For PG, the above isn't a problem as it doesn't have the stick read time logic. CREATE INDEX NONCONCURRENTLY does the following
- few catalog reads
- requests a SHARE lock which would wait for in progress inserts/updates and block newer ones once the lock is granted.
- If `TransactionIdIsValid(OldestXmin)` is true, takes the `SnapshotAny` path which totally skips MVCC and scans the raw tuples and indexes accordingly.
- If `TransactionIdIsValid(OldestXmin)` is false, requests the transaction snapshot and operates on it. Since earlier catalog reads do not affect the transaction snapshot here, PG doesn't run into the above issue.

In YB, despite taking `SHARE` lock on the parent table as PG and requesting the transaction snapshot, we still run into the stale read issue because of the sticky read time logic (with transactional ddl and object locking enabled, and/or concurrent ddl enabled).

This revision addresses the issue by forcing a latest snapshot before scanning the rows in the base table. Revision https://phorge.dev.yugabyte.com/D49199 enforced reset of read time when a new snapshot is registered, which forces the CREATE INDEX to pick a new read time here.

One other issue the revision fixes - `GetOldestNonRemovableTransactionId` could earlier return garbage value when `IsYugaByteEnabled()` is true because the fields of `ComputeXidHorizonsResult horizons` are being accessed without initialization.
```
TransactionId
GetOldestNonRemovableTransactionId(Relation rel)
{
  ComputeXidHorizonsResult horizons;
  ComputeXidHorizons(&horizons);        // returns early without doing any work since YB is enabled
  ...                                                              // access fields of horizons and return them based on in rel
}
```

**Note**
1. The revision fixes the issue independent of transactional ddl/object locking/concurrent ddl at the first place.
2. The newly registered `GetLatestSnapshot` is unregistered after the index is built, so the subsequent DML statements in the same transaction block would observe the same state as earlier in case of snapshot isolation. For instance,
```
begin;
UPDATE test SET v=100 WHERE k=4;
                                        begin;
                                        select * from test;
                                        -- would see k,v pair 4,4
                                        CREATE INDEX idx_test ON test(v);
                                        -- waits...
commit;
                                        -- ...resumes and rightly builds index with v=100
commit;                                 select * from test;
                                        -- would still see k,v pair 4,4
```
3. Anomaly with RR transactions that establish a read time prior to CREATE INDEX NON CONCURRENTLY
```
begin rr;
select * from test where v=4;
-- sees 4,4                         begin rr;
                                    delete from test where v=4;         begin rr;
                                                                        create index idx_test ON test(v);
                                                                        -- waits for delete to commit
                                    commit;
                                                                        -- resumes
                                                                        -- PG indexes v=4 too,
                                                                        -- while YB doesn't
                                                                        commit;
set enable_seqscan = off;
select * from test where v=4;
-- PG sees 1 row
-- YB sees 0 row
--
-- PG hits a serialization error
-- UPDATE SET v=v+100 WHERE v=4
-- while YB doesn't find the row
--
-- but PG can write the record
-- to a different table, while
-- YB doesn't since it doesn't
-- see the row at the first place
-- INSERT into another_test(k,v)
-- SELECT * FROM test WHERE v=4;
```
so the issue in YB is with concurrent repeatable read transactions which already established a read time now might see wrong results when using the index (violating snapshot isolation guarantees). There's some planned work to error requests accessing tables with request's read time < table's "birth time". This anomaly would be resolved then.

Test Plan:
Jenkins

```
./yb_build.sh release --java-test org.yb.pgsql.TestPgRegressIsolationObjectLocking#testPgRegress
```

Reviewers: sanketh, pjain, patnaik.balivada, smishra, #db-approvers

Reviewed By: patnaik.balivada

Subscribers: svc_phabricator, ybase, yql

Differential Revision: https://phorge.dev.yugabyte.com/D52199